-- ============================================================
-- DEMO SEED DATA
-- Simulates 8 real users with posts, replies, likes, reposts,
-- follows, and notifications (generated by triggers).
-- All users password: password123
-- ============================================================

-- ============================================================
-- 1. CREATE AUTH USERS (password: password123)
-- ============================================================
INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token,
  email_change, email_change_token_new, email_change_token_current,
  email_change_confirm_status, phone_change, phone_change_token,
  raw_app_meta_data, raw_user_meta_data, is_super_admin
) VALUES
  ('a1111111-1111-1111-1111-111111111111', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'alice@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '30 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('b2222222-2222-2222-2222-222222222222', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'bob@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '28 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('c3333333-3333-3333-3333-333333333333', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'carol@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '25 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('d4444444-4444-4444-4444-444444444444', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'dave@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '20 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('e5555555-5555-5555-5555-555555555555', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'emma@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '18 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('f6666666-6666-6666-6666-666666666666', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'frank@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '15 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('a7777777-7777-7777-7777-777777777777', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'grace@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '12 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false),

  ('b8888888-8888-8888-8888-888888888888', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
   'henry@demo.com', '$2a$10$N9ujuqUg97KHA7QWMjxecOzHNoGp.BUtUGubUeBaYxsQ9rzM//giq',
   now(), now() - interval '10 days', now(), '', '',
   '', '', '', 0, '', '',
   '{"provider":"email","providers":["email"]}', '{}', false);

-- Auth identities (required for email/password login)
INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) VALUES
  (gen_random_uuid(), 'a1111111-1111-1111-1111-111111111111', 'a1111111-1111-1111-1111-111111111111',
   jsonb_build_object('sub', 'a1111111-1111-1111-1111-111111111111', 'email', 'alice@demo.com'),
   'email', now(), now() - interval '30 days', now()),
  (gen_random_uuid(), 'b2222222-2222-2222-2222-222222222222', 'b2222222-2222-2222-2222-222222222222',
   jsonb_build_object('sub', 'b2222222-2222-2222-2222-222222222222', 'email', 'bob@demo.com'),
   'email', now(), now() - interval '28 days', now()),
  (gen_random_uuid(), 'c3333333-3333-3333-3333-333333333333', 'c3333333-3333-3333-3333-333333333333',
   jsonb_build_object('sub', 'c3333333-3333-3333-3333-333333333333', 'email', 'carol@demo.com'),
   'email', now(), now() - interval '25 days', now()),
  (gen_random_uuid(), 'd4444444-4444-4444-4444-444444444444', 'd4444444-4444-4444-4444-444444444444',
   jsonb_build_object('sub', 'd4444444-4444-4444-4444-444444444444', 'email', 'dave@demo.com'),
   'email', now(), now() - interval '20 days', now()),
  (gen_random_uuid(), 'e5555555-5555-5555-5555-555555555555', 'e5555555-5555-5555-5555-555555555555',
   jsonb_build_object('sub', 'e5555555-5555-5555-5555-555555555555', 'email', 'emma@demo.com'),
   'email', now(), now() - interval '18 days', now()),
  (gen_random_uuid(), 'f6666666-6666-6666-6666-666666666666', 'f6666666-6666-6666-6666-666666666666',
   jsonb_build_object('sub', 'f6666666-6666-6666-6666-666666666666', 'email', 'frank@demo.com'),
   'email', now(), now() - interval '15 days', now()),
  (gen_random_uuid(), 'a7777777-7777-7777-7777-777777777777', 'a7777777-7777-7777-7777-777777777777',
   jsonb_build_object('sub', 'a7777777-7777-7777-7777-777777777777', 'email', 'grace@demo.com'),
   'email', now(), now() - interval '12 days', now()),
  (gen_random_uuid(), 'b8888888-8888-8888-8888-888888888888', 'b8888888-8888-8888-8888-888888888888',
   jsonb_build_object('sub', 'b8888888-8888-8888-8888-888888888888', 'email', 'henry@demo.com'),
   'email', now(), now() - interval '10 days', now());

-- ============================================================
-- 2. PUBLIC USER PROFILES
-- ============================================================
INSERT INTO public.users (id, username, display_name, bio, created_at) VALUES
  ('a1111111-1111-1111-1111-111111111111', 'alice',   'Alice Johnson',   'Full-stack developer. Flutter & Dart enthusiast. Building cool stuff daily.',    now() - interval '30 days'),
  ('b2222222-2222-2222-2222-222222222222', 'bob',     'Bob Martinez',    'DevOps engineer at CloudScale. Kubernetes, Terraform, and too much coffee.',     now() - interval '28 days'),
  ('c3333333-3333-3333-3333-333333333333', 'carol',   'Carol Chen',      'UX designer turned developer. Pixel-perfect or bust. Figma addict.',             now() - interval '25 days'),
  ('d4444444-4444-4444-4444-444444444444', 'dave',    'Dave Wilson',     'Indie hacker. Shipping products nobody asked for since 2019.',                   now() - interval '20 days'),
  ('e5555555-5555-5555-5555-555555555555', 'emma',    'Emma Thompson',   'Data scientist. Python, R, and a dangerous amount of pandas (the library).',     now() - interval '18 days'),
  ('f6666666-6666-6666-6666-666666666666', 'frank',   'Frank Nakamura',  'Backend engineer. Rust evangelist. Will debate you about memory safety.',        now() - interval '15 days'),
  ('a7777777-7777-7777-7777-777777777777', 'grace',   'Grace Okafor',    'Mobile dev. React Native refugee, now happily using Flutter.',                   now() - interval '12 days'),
  ('b8888888-8888-8888-8888-888888888888', 'henry',   'Henry Park',      'Startup founder. Previously at Google. Currently caffeinated.',                  now() - interval '10 days');

-- ============================================================
-- 3. FOLLOWS (realistic social graph)
-- Triggers will create follow notifications automatically
-- ============================================================
INSERT INTO public.followers (follower_id, following_id, created_at) VALUES
  -- Alice follows: Bob, Carol, Dave, Emma, Grace
  ('a1111111-1111-1111-1111-111111111111', 'b2222222-2222-2222-2222-222222222222', now() - interval '27 days'),
  ('a1111111-1111-1111-1111-111111111111', 'c3333333-3333-3333-3333-333333333333', now() - interval '25 days'),
  ('a1111111-1111-1111-1111-111111111111', 'd4444444-4444-4444-4444-444444444444', now() - interval '20 days'),
  ('a1111111-1111-1111-1111-111111111111', 'e5555555-5555-5555-5555-555555555555', now() - interval '18 days'),
  ('a1111111-1111-1111-1111-111111111111', 'a7777777-7777-7777-7777-777777777777', now() - interval '11 days'),
  -- Bob follows: Alice, Carol, Frank, Henry
  ('b2222222-2222-2222-2222-222222222222', 'a1111111-1111-1111-1111-111111111111', now() - interval '26 days'),
  ('b2222222-2222-2222-2222-222222222222', 'c3333333-3333-3333-3333-333333333333', now() - interval '24 days'),
  ('b2222222-2222-2222-2222-222222222222', 'f6666666-6666-6666-6666-666666666666', now() - interval '14 days'),
  ('b2222222-2222-2222-2222-222222222222', 'b8888888-8888-8888-8888-888888888888', now() - interval '9 days'),
  -- Carol follows: Alice, Bob, Emma, Grace, Henry
  ('c3333333-3333-3333-3333-333333333333', 'a1111111-1111-1111-1111-111111111111', now() - interval '24 days'),
  ('c3333333-3333-3333-3333-333333333333', 'b2222222-2222-2222-2222-222222222222', now() - interval '23 days'),
  ('c3333333-3333-3333-3333-333333333333', 'e5555555-5555-5555-5555-555555555555', now() - interval '17 days'),
  ('c3333333-3333-3333-3333-333333333333', 'a7777777-7777-7777-7777-777777777777', now() - interval '11 days'),
  ('c3333333-3333-3333-3333-333333333333', 'b8888888-8888-8888-8888-888888888888', now() - interval '9 days'),
  -- Dave follows: Alice, Bob, Frank
  ('d4444444-4444-4444-4444-444444444444', 'a1111111-1111-1111-1111-111111111111', now() - interval '19 days'),
  ('d4444444-4444-4444-4444-444444444444', 'b2222222-2222-2222-2222-222222222222', now() - interval '18 days'),
  ('d4444444-4444-4444-4444-444444444444', 'f6666666-6666-6666-6666-666666666666', now() - interval '13 days'),
  -- Emma follows: Alice, Carol, Dave, Grace, Henry
  ('e5555555-5555-5555-5555-555555555555', 'a1111111-1111-1111-1111-111111111111', now() - interval '17 days'),
  ('e5555555-5555-5555-5555-555555555555', 'c3333333-3333-3333-3333-333333333333', now() - interval '16 days'),
  ('e5555555-5555-5555-5555-555555555555', 'd4444444-4444-4444-4444-444444444444', now() - interval '15 days'),
  ('e5555555-5555-5555-5555-555555555555', 'a7777777-7777-7777-7777-777777777777', now() - interval '10 days'),
  ('e5555555-5555-5555-5555-555555555555', 'b8888888-8888-8888-8888-888888888888', now() - interval '8 days'),
  -- Frank follows: Bob, Dave, Henry
  ('f6666666-6666-6666-6666-666666666666', 'b2222222-2222-2222-2222-222222222222', now() - interval '14 days'),
  ('f6666666-6666-6666-6666-666666666666', 'd4444444-4444-4444-4444-444444444444', now() - interval '13 days'),
  ('f6666666-6666-6666-6666-666666666666', 'b8888888-8888-8888-8888-888888888888', now() - interval '8 days'),
  -- Grace follows: Alice, Carol, Emma, Frank
  ('a7777777-7777-7777-7777-777777777777', 'a1111111-1111-1111-1111-111111111111', now() - interval '11 days'),
  ('a7777777-7777-7777-7777-777777777777', 'c3333333-3333-3333-3333-333333333333', now() - interval '10 days'),
  ('a7777777-7777-7777-7777-777777777777', 'e5555555-5555-5555-5555-555555555555', now() - interval '9 days'),
  ('a7777777-7777-7777-7777-777777777777', 'f6666666-6666-6666-6666-666666666666', now() - interval '8 days'),
  -- Henry follows: Alice, Bob, Dave, Emma, Frank, Grace
  ('b8888888-8888-8888-8888-888888888888', 'a1111111-1111-1111-1111-111111111111', now() - interval '9 days'),
  ('b8888888-8888-8888-8888-888888888888', 'b2222222-2222-2222-2222-222222222222', now() - interval '9 days'),
  ('b8888888-8888-8888-8888-888888888888', 'd4444444-4444-4444-4444-444444444444', now() - interval '8 days'),
  ('b8888888-8888-8888-8888-888888888888', 'e5555555-5555-5555-5555-555555555555', now() - interval '7 days'),
  ('b8888888-8888-8888-8888-888888888888', 'f6666666-6666-6666-6666-666666666666', now() - interval '6 days'),
  ('b8888888-8888-8888-8888-888888888888', 'a7777777-7777-7777-7777-777777777777', now() - interval '5 days');

-- ============================================================
-- 4. POSTS (25 main posts with realistic tech Twitter content)
-- Triggers will handle replies_count when replies are inserted
-- ============================================================
INSERT INTO public.posts (id, user_id, content, created_at) VALUES
  ('10000000-0000-0000-0000-000000000001', 'a1111111-1111-1111-1111-111111111111',
   'Just set up my new Flutter project with Riverpod v3. The code generation is so much cleaner now. No more ConsumerWidget boilerplate everywhere!',
   now() - interval '26 days'),
  ('10000000-0000-0000-0000-000000000002', 'b2222222-2222-2222-2222-222222222222',
   'Hot take: Kubernetes is overkill for 90% of startups. A single VPS with Docker Compose will take you further than you think.',
   now() - interval '25 days'),
  ('10000000-0000-0000-0000-000000000003', 'c3333333-3333-3333-3333-333333333333',
   'Spent 3 hours perfecting a button animation that users will see for 0.3 seconds. Worth it? Absolutely.',
   now() - interval '24 days'),
  ('10000000-0000-0000-0000-000000000004', 'd4444444-4444-4444-4444-444444444444',
   'Launched my new side project today! It''s a CLI tool that generates commit messages from your diff. Already mass-adopted by exactly 1 user (me).',
   now() - interval '19 days'),
  ('10000000-0000-0000-0000-000000000005', 'a1111111-1111-1111-1111-111111111111',
   'PSA: If you''re using Freezed v3, remember to use "sealed class" instead of plain "class". Spent an hour debugging that one.',
   now() - interval '18 days'),
  ('10000000-0000-0000-0000-000000000006', 'e5555555-5555-5555-5555-555555555555',
   'Just finished a paper on transformer attention patterns in time series forecasting. The results are surprisingly good for energy consumption prediction.',
   now() - interval '17 days'),
  ('10000000-0000-0000-0000-000000000007', 'b2222222-2222-2222-2222-222222222222',
   'Finally migrated our CI/CD from Jenkins to GitHub Actions. Build times went from 45min to 8min. Should have done this years ago.',
   now() - interval '16 days'),
  ('10000000-0000-0000-0000-000000000008', 'f6666666-6666-6666-6666-666666666666',
   'Rewrote our Python microservice in Rust. 10x throughput, 50x less memory. The 2-week rewrite paid for itself in the first AWS bill.',
   now() - interval '15 days'),
  ('10000000-0000-0000-0000-000000000009', 'c3333333-3333-3333-3333-333333333333',
   'Design tip: Stop using pure black (#000000) for text. Use #1a1a2e or similar dark grays. Your users'' eyes will thank you.',
   now() - interval '13 days'),
  ('10000000-0000-0000-0000-000000000010', 'a7777777-7777-7777-7777-777777777777',
   'Switched from React Native to Flutter 6 months ago. The developer experience is night and day. Hot reload actually works consistently.',
   now() - interval '12 days'),
  ('10000000-0000-0000-0000-000000000011', 'b8888888-8888-8888-8888-888888888888',
   'Startup advice nobody asks for: Your first 10 customers don''t care about your tech stack. They care if you solve their problem.',
   now() - interval '11 days'),
  ('10000000-0000-0000-0000-000000000012', 'd4444444-4444-4444-4444-444444444444',
   'My side project hit 100 stars on GitHub! That''s roughly 100 people who starred it and 3 who actually use it.',
   now() - interval '10 days'),
  ('10000000-0000-0000-0000-000000000013', 'a1111111-1111-1111-1111-111111111111',
   'Supabase with local Docker is such a game changer. Full Postgres + Auth + Storage + Realtime running locally. No more "works on my machine" excuses.',
   now() - interval '9 days'),
  ('10000000-0000-0000-0000-000000000014', 'e5555555-5555-5555-5555-555555555555',
   'People keep asking if AI will replace data scientists. My model just predicted that next Tuesday will be a Wednesday. We''re safe for now.',
   now() - interval '8 days'),
  ('10000000-0000-0000-0000-000000000015', 'f6666666-6666-6666-6666-666666666666',
   'The Rust borrow checker rejected my code 47 times today. On attempt 48, I finally understood lifetimes. I think. Maybe.',
   now() - interval '7 days'),
  ('10000000-0000-0000-0000-000000000016', 'b2222222-2222-2222-2222-222222222222',
   'Terraform destroyed our staging environment because someone ran "terraform apply" without checking the plan. Always. Check. The. Plan.',
   now() - interval '6 days'),
  ('10000000-0000-0000-0000-000000000017', 'a7777777-7777-7777-7777-777777777777',
   'Built a beautiful animated bottom sheet in Flutter today. Curves.easeOutBack is chef''s kiss for that bouncy feel.',
   now() - interval '5 days'),
  ('10000000-0000-0000-0000-000000000018', 'c3333333-3333-3333-3333-333333333333',
   'Every designer should learn to code. Not to become a developer, but to understand what''s possible and have better conversations with your team.',
   now() - interval '4 days'),
  ('10000000-0000-0000-0000-000000000019', 'b8888888-8888-8888-8888-888888888888',
   'Closed our seed round today! $2.5M to build developer tools. Incredibly grateful to our investors who believed in the vision. Time to hire!',
   now() - interval '3 days'),
  ('10000000-0000-0000-0000-000000000020', 'd4444444-4444-4444-4444-444444444444',
   'The best code I wrote today was the code I deleted. Removed 2,000 lines of "just in case" abstractions. The codebase breathes again.',
   now() - interval '2 days'),
  ('10000000-0000-0000-0000-000000000021', 'a1111111-1111-1111-1111-111111111111',
   'GoRouter tip: Use shellRoute for your bottom navigation, and push new routes on top of it. Keeps the nav bar visible on main tabs, hidden on detail pages.',
   now() - interval '1 day'),
  ('10000000-0000-0000-0000-000000000022', 'e5555555-5555-5555-5555-555555555555',
   'Finally got my Jupyter notebook workflow right: VS Code + Copilot + a good conda environment. Feels like having a research assistant.',
   now() - interval '18 hours'),
  ('10000000-0000-0000-0000-000000000023', 'f6666666-6666-6666-6666-666666666666',
   'Just published my first Rust crate! It''s a zero-copy JSON parser optimized for streaming. 3x faster than serde for large payloads.',
   now() - interval '12 hours'),
  ('10000000-0000-0000-0000-000000000024', 'a7777777-7777-7777-7777-777777777777',
   'Pro tip for Flutter devs: Use RepaintBoundary around expensive widgets. Just wrapped our dashboard charts and FPS jumped from 45 to 60.',
   now() - interval '6 hours'),
  ('10000000-0000-0000-0000-000000000025', 'b8888888-8888-8888-8888-888888888888',
   'Hiring is so much harder than building product. If you''re a senior Flutter dev who wants to work on devtools, DM me!',
   now() - interval '2 hours');

-- ============================================================
-- 5. REPLIES (threaded conversations)
-- Triggers will update replies_count on parent + create notifications
-- ============================================================
INSERT INTO public.posts (id, user_id, content, reply_to_id, created_at) VALUES
  -- Replies to Alice's Riverpod post
  ('20000000-0000-0000-0000-000000000001', 'b2222222-2222-2222-2222-222222222222',
   'Totally agree! The @riverpod annotation is so much cleaner than manually writing all the provider types.',
   '10000000-0000-0000-0000-000000000001', now() - interval '25 days 22 hours'),
  ('20000000-0000-0000-0000-000000000002', 'a7777777-7777-7777-7777-777777777777',
   'Same experience here! The generated code is also much easier to debug when something goes wrong.',
   '10000000-0000-0000-0000-000000000001', now() - interval '25 days 20 hours'),

  -- Replies to Bob's Kubernetes hot take
  ('20000000-0000-0000-0000-000000000003', 'f6666666-6666-6666-6666-666666666666',
   'Depends on your scaling needs, but for most CRUD apps, absolutely. K8s complexity isn''t free.',
   '10000000-0000-0000-0000-000000000002', now() - interval '24 days 20 hours'),
  ('20000000-0000-0000-0000-000000000004', 'd4444444-4444-4444-4444-444444444444',
   'This. I ran my SaaS on a $20/mo VPS for the first year. Scaled to 500 users before needing anything more.',
   '10000000-0000-0000-0000-000000000002', now() - interval '24 days 18 hours'),
  ('20000000-0000-0000-0000-000000000005', 'b2222222-2222-2222-2222-222222222222',
   'To be fair, once you hit multi-region, K8s starts to make a lot of sense. But most never get there.',
   '10000000-0000-0000-0000-000000000002', now() - interval '24 days 16 hours'),

  -- Replies to Dave's side project launch
  ('20000000-0000-0000-0000-000000000006', 'a1111111-1111-1111-1111-111111111111',
   'Congrats on shipping! Link? I''d love to try it out. AI-generated commit messages are my guilty pleasure.',
   '10000000-0000-0000-0000-000000000004', now() - interval '18 days 22 hours'),
  ('20000000-0000-0000-0000-000000000007', 'b8888888-8888-8888-8888-888888888888',
   'The "1 user is me" stage is where every great product starts. Keep iterating!',
   '10000000-0000-0000-0000-000000000004', now() - interval '18 days 20 hours'),

  -- Replies to Frank's Rust rewrite
  ('20000000-0000-0000-0000-000000000008', 'b2222222-2222-2222-2222-222222222222',
   'Those are impressive numbers. What was the service doing? API gateway or something compute-heavy?',
   '10000000-0000-0000-0000-000000000008', now() - interval '14 days 20 hours'),
  ('20000000-0000-0000-0000-000000000009', 'f6666666-6666-6666-6666-666666666666',
   'It was a real-time data ingestion pipeline. Parsing JSON, validating, and writing to Kafka. Perfect Rust use case.',
   '10000000-0000-0000-0000-000000000008', now() - interval '14 days 18 hours'),
  ('20000000-0000-0000-0000-000000000010', 'e5555555-5555-5555-5555-555555555555',
   'We had a similar pipeline in Python. Might need to look into Rust for the hot path. Any good resources for getting started?',
   '10000000-0000-0000-0000-000000000008', now() - interval '14 days 16 hours'),

  -- Replies to Henry's seed round announcement
  ('20000000-0000-0000-0000-000000000011', 'a1111111-1111-1111-1111-111111111111',
   'Congrats Henry! DevTools are so underinvested. Excited to see what you build.',
   '10000000-0000-0000-0000-000000000019', now() - interval '2 days 22 hours'),
  ('20000000-0000-0000-0000-000000000012', 'd4444444-4444-4444-4444-444444444444',
   'Amazing news! As a fellow devtools builder, I know how hard it is to get funding in this space. Well deserved.',
   '10000000-0000-0000-0000-000000000019', now() - interval '2 days 20 hours'),
  ('20000000-0000-0000-0000-000000000013', 'c3333333-3333-3333-3333-333333333333',
   'If you need a designer who understands devtools UX, you know where to find me!',
   '10000000-0000-0000-0000-000000000019', now() - interval '2 days 18 hours'),
  ('20000000-0000-0000-0000-000000000014', 'e5555555-5555-5555-5555-555555555555',
   'Huge congrats! Will you be integrating any ML-powered features? Would love to chat about that.',
   '10000000-0000-0000-0000-000000000019', now() - interval '2 days 16 hours'),

  -- Reply to Alice's Supabase post
  ('20000000-0000-0000-0000-000000000015', 'a7777777-7777-7777-7777-777777777777',
   'Supabase local dev is incredible. The CLI makes it so easy to manage migrations too.',
   '10000000-0000-0000-0000-000000000013', now() - interval '8 days 20 hours'),

  -- Reply to Emma's AI joke
  ('20000000-0000-0000-0000-000000000016', 'c3333333-3333-3333-3333-333333333333',
   'Haha! To be fair, predicting that next Tuesday is a Wednesday would be impressive for a neural net.',
   '10000000-0000-0000-0000-000000000014', now() - interval '7 days 20 hours'),

  -- Replies to Frank's Rust crate
  ('20000000-0000-0000-0000-000000000017', 'b2222222-2222-2222-2222-222222222222',
   'Zero-copy parsing is where Rust really shines. Will definitely check this out for our log ingestion pipeline.',
   '10000000-0000-0000-0000-000000000023', now() - interval '10 hours'),
  ('20000000-0000-0000-0000-000000000018', 'd4444444-4444-4444-4444-444444444444',
   'Just looked at the repo - the API design is really clean. The streaming iterator pattern is a nice touch.',
   '10000000-0000-0000-0000-000000000023', now() - interval '8 hours');

-- ============================================================
-- 6. LIKES (triggers update likes_count + create notifications)
-- ============================================================
INSERT INTO public.likes (user_id, post_id, created_at) VALUES
  -- Alice's Riverpod post (5 likes)
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000001', now() - interval '25 days 23 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000001', now() - interval '25 days 22 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000001', now() - interval '25 days 20 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000001', now() - interval '25 days 18 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000001', now() - interval '25 days 15 hours'),
  -- Bob's K8s take (4 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 23 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 20 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 18 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 15 hours'),
  -- Carol's animation post (3 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000003', now() - interval '23 days 22 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000003', now() - interval '23 days 20 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000003', now() - interval '23 days 18 hours'),
  -- Dave's launch (6 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 22 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 20 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 18 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 16 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 14 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 12 hours'),
  -- Alice's Freezed tip (3 likes)
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000005', now() - interval '17 days 22 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000005', now() - interval '17 days 20 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000005', now() - interval '17 days 18 hours'),
  -- Emma's paper (2 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000006', now() - interval '16 days 22 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000006', now() - interval '16 days 20 hours'),
  -- Frank's Rust rewrite (7 likes - viral)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 22 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 20 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 18 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 16 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 14 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 12 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 10 hours'),
  -- Carol's design tip (4 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 22 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 20 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 18 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 16 hours'),
  -- Grace's Flutter switch (2 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000010', now() - interval '11 days 22 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000010', now() - interval '11 days 20 hours'),
  -- Henry's startup advice (3 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000011', now() - interval '10 days 22 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000011', now() - interval '10 days 20 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000011', now() - interval '10 days 18 hours'),
  -- Alice's Supabase post (4 likes)
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000013', now() - interval '8 days 22 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000013', now() - interval '8 days 20 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000013', now() - interval '8 days 18 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000013', now() - interval '8 days 16 hours'),
  -- Emma's AI joke (7 likes - most popular)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 22 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 20 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 18 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 16 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 14 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 12 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 10 hours'),
  -- Terraform disaster (3 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000016', now() - interval '5 days 22 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000016', now() - interval '5 days 20 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000016', now() - interval '5 days 18 hours'),
  -- Henry's funding (7 likes - viral)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 22 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 21 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 20 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 19 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 18 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 17 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 16 hours'),
  -- Dave's code deletion (4 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000020', now() - interval '1 day 22 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000020', now() - interval '1 day 20 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000020', now() - interval '1 day 18 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000020', now() - interval '1 day 16 hours'),
  -- Alice's GoRouter tip (3 likes)
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000021', now() - interval '20 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000021', now() - interval '18 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000021', now() - interval '16 hours'),
  -- Frank's Rust crate (4 likes)
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000023', now() - interval '10 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000023', now() - interval '8 hours'),
  ('e5555555-5555-5555-5555-555555555555', '10000000-0000-0000-0000-000000000023', now() - interval '6 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000023', now() - interval '4 hours'),
  -- Grace's RepaintBoundary tip (2 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000024', now() - interval '4 hours'),
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000024', now() - interval '3 hours'),
  -- Henry's hiring (2 likes)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000025', now() - interval '1 hour'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000025', now() - interval '45 minutes'),
  -- Some likes on replies
  ('a1111111-1111-1111-1111-111111111111', '20000000-0000-0000-0000-000000000001', now() - interval '25 days 21 hours'),
  ('c3333333-3333-3333-3333-333333333333', '20000000-0000-0000-0000-000000000004', now() - interval '24 days 17 hours'),
  ('b2222222-2222-2222-2222-222222222222', '20000000-0000-0000-0000-000000000006', now() - interval '18 days 21 hours'),
  ('d4444444-4444-4444-4444-444444444444', '20000000-0000-0000-0000-000000000007', now() - interval '18 days 19 hours'),
  ('f6666666-6666-6666-6666-666666666666', '20000000-0000-0000-0000-000000000009', now() - interval '14 days 17 hours'),
  ('b8888888-8888-8888-8888-888888888888', '20000000-0000-0000-0000-000000000011', now() - interval '2 days 21 hours'),
  ('a1111111-1111-1111-1111-111111111111', '20000000-0000-0000-0000-000000000013', now() - interval '2 days 17 hours');

-- ============================================================
-- 7. REPOSTS (triggers update reposts_count + create notifications)
-- ============================================================
INSERT INTO public.reposts (user_id, post_id, created_at) VALUES
  -- Bob's K8s take reposted
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 22 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000002', now() - interval '24 days 20 hours'),
  -- Dave's launch
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 21 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000004', now() - interval '18 days 19 hours'),
  -- Alice's Freezed tip
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000005', now() - interval '17 days 21 hours'),
  -- Frank's Rust rewrite (most reposted - 4)
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 21 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 19 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 17 hours'),
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000008', now() - interval '14 days 15 hours'),
  -- Carol's design tip
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 21 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000009', now() - interval '12 days 19 hours'),
  -- Emma's AI joke
  ('c3333333-3333-3333-3333-333333333333', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 21 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 19 hours'),
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000014', now() - interval '7 days 17 hours'),
  -- Henry's funding (4 reposts)
  ('a1111111-1111-1111-1111-111111111111', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 21 hours'),
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 19 hours'),
  ('d4444444-4444-4444-4444-444444444444', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 17 hours'),
  ('f6666666-6666-6666-6666-666666666666', '10000000-0000-0000-0000-000000000019', now() - interval '2 days 15 hours'),
  -- Alice's GoRouter tip
  ('a7777777-7777-7777-7777-777777777777', '10000000-0000-0000-0000-000000000021', now() - interval '19 hours'),
  -- Frank's Rust crate
  ('b2222222-2222-2222-2222-222222222222', '10000000-0000-0000-0000-000000000023', now() - interval '9 hours'),
  ('b8888888-8888-8888-8888-888888888888', '10000000-0000-0000-0000-000000000023', now() - interval '5 hours');

-- ============================================================
-- 8. Mark older notifications as read (realistic behavior)
-- ============================================================
UPDATE public.notifications
SET is_read = true
WHERE created_at < now() - interval '3 days';
